apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - pairs:
      app.kubernetes.io/name: work-t3code
    includeSelectors: false

resources:
  - t3state-pvc.yaml
  - claude-oauth.yaml
  - depot-token.yaml
  - netpol.yaml
  - service.yaml
  - statefulset.yaml

components:
  - ../../components/labels
