apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - pairs:
      app.kubernetes.io/name: tailscale
    includeSelectors: false

# The operator itself is helm-installed with ../values.yaml (../README.md).
resources:
  - namespace.yaml
  - operator-oauth.yaml

components:
  - ../../components/labels
