apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: agents

labels:
  - pairs:
      app.kubernetes.io/part-of: homelab
      app.kubernetes.io/managed-by: kustomize
    includeSelectors: false

resources:
  - externalsecret.yaml
  - deployment-knowledge-ingest.yaml
  - deployment-knowledge-retrieval.yaml
  - service-knowledge-ingest.yaml
  - service-knowledge-retrieval.yaml
  - netpol-knowledge.yaml
