apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: agents

labels:
  - pairs:
      app.kubernetes.io/name: knowledge
    includeSelectors: false

resources:
  - externalsecret.yaml
  - deployment-knowledge-ingest.yaml
  - deployment-knowledge-retrieval.yaml
  - service-knowledge-ingest.yaml
  - ingress-knowledge.yaml
  - netpol-knowledge.yaml

components:
  - ../../components/labels
