apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - pairs:
      app.kubernetes.io/part-of: homelab
      app.kubernetes.io/managed-by: kustomize
    includeSelectors: false

resources:
  - cluster-image-catalog.yaml
  - cluster.yaml
  - databases.yaml
  - netpol.yaml
  - pdb.yaml
