apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: onepassword
  namespace: database
spec:
  provider:
    onepasswordSDK:
      vault: homelab
      auth:
        serviceAccountSecretRef:
          name: onepassword-service-account
          key: token
