apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - pairs:
      app.kubernetes.io/part-of: homelab
    includeSelectors: false

resources:
  - collector-cronjob.yaml
  - reconciler-cronjob.yaml
  - profile-code-pr.yaml
  - profile-security.yaml
  - profile-reviewer.yaml
  - orchestrator-cronjob.yaml
  - security-cronjob.yaml
  - reviewer-cronjob.yaml
