apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - priorityclasses.yaml
  - networkpolicy.yaml
  - kube-api-egress.yaml
  - egress-canary.yaml

components:
  - ../../components/labels
  - ../../../clusters/home/node
