apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - pairs:
      app.kubernetes.io/part-of: homelab
    includeSelectors: false

resources:
  - loki.yaml
  - alloy.yaml
  - rbac.yaml
  - netpol.yaml
  - grafana-datasource.yaml
